CREATE TABLE Event (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	IPv4 TEXT,
	IPv6 TEXT,
	Timezone VARCHAR(128),
	ScreenWidth INT,
	ScreenHeight INT,
	NumCPUCores INT,
	Language VARCHAR(64),
	UserAgent VARCHAR(128),
	CanvasHash VARCHAR(64),
	Genesis TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Mutated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
